title: Tsunashima Ryuta
baseurl: /
destination: ../takashift.github.io/
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: 綱島隆太
  tagline: >
    筑波大学<br>
    理工情報生命学術院<br>
    システム情報工学研究群<br>
    情報理工学位プログラム<br>
    博士後期課程1年
  profile_img: images/It's me!!!!!.jpg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; 綱島隆太. All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
